### ISSUE TITLE
"An SQL error occurred: SQLSTATE [23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous"}

### ISSUE THREAD

**Issue by mumus** [emran/ssp#14]
If two tables has field 'id' this error will appear

**Comment by orthodoxws** [comment]
Yes, I am having the same problem.  Is there a solution to two tables who both have 'id' columns?

**Comment by emran** [comment]
To Integrity constraint violation, I have added the option to rename any field name.
You can rename the `id` field for both table or whatever you need.
Like this you can define your column array.
`
$columns = array(
    array( 'db' => '`table1`.`id`',       'dt' => 0, 'field' => 'id', 'as' => 'table1_id' ),
    array( 'db' => '`table2`.`id`',    'dt' => 1  'field' => 'login', 'as' => 'table2_id'),
`

I think, it may help you.
