### ISSUE TITLE
Null everywhere

### ISSUE THREAD

**Issue by andreaballarin** [emran/ssp#26]
**Hi, hope you can help me.
this is my result when i call ajax function:**

{"draw":1,"recordsTotal":236,"recordsFiltered":236,"data":[[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null],[null,null,null,null,null,null]]}

**and this is the code I call with ajax**

`<?php
require_once('../includes/load.php');
page_require_level(3);

$table = 'products';

$primaryKey = 'id';

$columns = array(
    array( 'db' => '`products`.`name`',     'dt' => 0, 'field' => 'p_name'),
    array( 'db' => '`products`.`note`',     'dt' => 1, 'field' => 'p_note'  ),
    array( 'db' => '`categories`.`name`',   'dt' => 2, 'field' => 'c_name'),
    array( 'db' => '`producer`.`name`',     'dt' => 3, 'field' => 'pro_name' ),
    array( 'db' => '`products`.`prezzo`',   'dt' => 4, 'field' => 'p_prezzo' ),
    array( 'db' => '`products`.`quantity`', 'dt' => 5, 'field' => 'p_quantity' )
);

require('../includes/config.php');
$sql_details = array(
    'user' => DB_USER,
    'pass' => DB_PASS,
    'db'   => DB_NAME,
    'host' => DB_HOST
);

require('ssp.class.php');

$joinQuery = "FROM `products` LEFT JOIN `categories` ON `products`.`categories_id` = `categories`.`id` LEFT JOIN `producer` ON `products`.`producer_id` = `producer`.`id`";
$extraWhere = "";
$groupBy = "";
$having = "";

echo json_encode(
	SSP::simple( $_GET, $sql_details, $table, $primaryKey, $columns, $joinQuery, $extraWhere, $groupBy, $having )
);`

**Comment by emran** [comment]
Hello,

The problem is in your column definition. 
If you want to rename the column name then you have to define the `as` index as well.

- `field` index determine the field you select
- `as` index determines the alias of column name

So your column would be like this

```
$columns = array(
array( 'db' => 'products.name', 'dt' => 0, 'field' => 'p_name', 'as' => 'p_name'),
array( 'db' => 'products.note', 'dt' => 1, 'field' => 'p_note', 'as' => 'p_note' ),
array( 'db' => 'categories.name', 'dt' => 2, 'field' => 'c_name', 'as' => 'c_name'),
array( 'db' => 'producer.name', 'dt' => 3, 'field' => 'pro_name', 'as' => 'pro_name' ),
array( 'db' => 'products.prezzo', 'dt' => 4, 'field' => 'p_prezzo', 'as' => 'p_prezzo' ),
array( 'db' => 'products.quantity', 'dt' => 5, 'field' => 'p_quantity', 'as' => 'p_quantity' )
);
```

**Comment by andreaballarin** [comment]
It work! Thank you so much
