### ISSUE TITLE
Error with cyrillic data in db fields

### ISSUE THREAD

**Issue by tagplus5** [emran/ssp#8]
In this part 

```
// Is there a formatter?
if ( isset( $column['formatter'] ) ) {
    $row[ $column['dt'] ] = ($isJoin) ? $column['formatter']( $data[$i][ $column['field'] ], $data[$i] ) : $column['formatter']( $data[$i][ $column['db'] ], $data[$i] );
}
else {
    $row[ $column['dt'] ] = htmlentities( ($isJoin) ? $data[$i][ $columns[$j]['field'] ] : $data[$i][ $columns[$j]['db'] ] );
}
```

If I have cyrrilic data in db fields i get null of wrong data.
Need to set "UTF-8"

```
$row[$column['dt']] = htmlentities(($isJoin) ? $data[$i][$column['field']] : $data[$i][$column['db']], null, "UTF-8");
```

**Comment by emran** [comment]
"UTF-8" is set at 303 no line at the customized script.
Have a look: https://github.com/emran/ssp/blob/master/example/scripts/ssp.customized.class.php
Is this the script you are using?

Setting "UTF-8" at that place is working for you or not please let me know.
Thanks for sharing your thoughts.

**Comment by tagplus5** [comment]
I use script https://github.com/emran/ssp/blob/master/ssp.php.
In this script need to set UTF8 for htmlentities than work well.
