### ISSUE TITLE
Get the value of some column and use in formater of another column

### ISSUE THREAD

**Issue by noveweb** [emran/ssp#9]
Hi, guy!

How can i get the value of some column and use in formater of another column?

Thanks!

$columns = array(
    array( 'db' => 'nome',                     'dt' => 0 ),  
	array( 'db' => 'email',                    'dt' => 1 ),   
	array(
        'db'        => 'timestamp',
        'dt'        => 2,
        'formatter' => function( $d, $row ) {
            return date('d/m/Y H:i', $d);
        }
    ),
	array(
        'db'        => 'ultimo_acesso',
        'dt'        => 3,
        'formatter' => function( $d, $row ) {
            return date('d/m/Y H:i', $d);
        }
    ),
	array(
        'db'        => 'id',
        'dt'        => 4,
        'formatter' => function( $d, $row ) {

   I WANT USE HERE THE VALUE FROM COLUMN "email"

            return "<a href='usuarios/administradores/editar/".$d."/' class='btn btn-xs btn-primary'><i class='fa fa-pencil'></i></a> <a id='administradores_".$d."' href='javascript:;' class='btn btn-xs btn-danger del'><i class='fa fa-trash'></i></a>";
        }
    )
);

**Comment by emran** [comment]
Within $row array param you have all the value of the present row. 
So you just get those value via their indexes.

Like you can get value of Email from $row[1] as `email` field index is 1. 

Cheers!! :+1:

**Comment by noveweb** [comment]
Thank you, guy!!!

2016-06-06 2:43 GMT-03:00 Md. Emran ul hadi <notifications@github.com>:

> Closed #9 <https://github.com/emran/ssp/issues/9>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/emran/ssp/issues/9#event-682417506>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AKrvVVoRTZPbp7Nl8daF1wDCz--Xu--Mks5qI7NrgaJpZM4ItEB7>
> .
>



--
